[package]
name = "nn"
version = "0.1.0"
authors = ["x1ah <x1ahgxq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
url = "2.1.1"
reqwest = { version = "0.10", features = ["blocking"] }
